name: app

type: php:7.3

runtime:
    extensions:
        - xsl
        - amqp
        - redis
        - apcu
        - mbstring
        - sodium
        - iconv
        - ctype
        - pdo_pgsql


build:
    flavor: none

relationships:
    database: "db:postgresql"
    redis: "rediscache:redis"
    rabbitmq: "queue:rabbitmq"

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

redisache:
    type: redis:5.0

disk: 512

mounts:
    "/var": { source: local, source_path: var }
    "/public/uploads": { source: service, service: files, source_path: uploads }

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)


workers:
    messages:
        commands:
            start: |
                set -x -e

                (>&2 symfony-deploy)
                php bin/console messenger:consume async -vv --time-limit 3600--memory-limit=128M
